esphome:
  name: esp-eth-cam
  friendly_name: esp eth cam

esp32:
  board: adafruit_feather_esp32s3_nopsram
  variant: esp32s3


# Enable logging
logger: 
#  level: VERY_VERBOSE
  hardware_uart: UART0

psram:
  mode: octal
  speed: 80MHz

# Enable Home Assistant API
api:
#  encryption:
#    key: "generate key here https://esphome.io/components/api"
ota:
  - platform: esphome
#  password: "ota password"


external_components:
- source:
    type: git
    url: https://github.com/MichaKersloot/esphome_custom_components
  components: [ esp32_camera ]


ethernet:
  type: W5500
  mosi_pin: GPIO1
  miso_pin: GPIO14
  clk_pin: GPIO21
  cs_pin: GPIO39
  interrupt_pin: GPIO38
  clock_speed: 25MHz
  use_address: 172.20.10.226

esp32_camera:
  name: My Camera
  external_clock:
    pin: GPIO15
    frequency: 20MHz
  i2c_pins:
    sda: GPIO4
    scl: GPIO5
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13
  resolution: 1024x768
  jpeg_quality: 10
