esphome:
  name: esp-eth-cam
  friendly_name: esp eth cam

esp32:
  board: adafruit_feather_esp32s3_nopsram
  framework:
    type: arduino
    version: 2.0.8

api:
#  encryption:
#    key: "generate key here https://esphome.io/components/api"

ota:
#  password: "ota password"

# Enable logging
logger: 
  level: VERY_VERBOSE
  hardware_uart: UART0
    
external_components:
- source:
    type: git
    url: https://github.com/JeroenVanOort/esphome/
    ref: eth-w5500
  components:
  - ethernet

- source:
    type: git
    url: https://github.com/MichaKersloot/esphome_custom_components
  components: [ esp32_camera ]

ethernet:
  type: W5500
  mosi_pin: GPIO35
  miso_pin: GPIO37
  clk_pin: GPIO36
  cs_pin: GPIO39
 # reset_pin: GPIO26
  interrupt_pin: GPIO38
  clock_speed: 10MHz

esp32_camera:
  name: My Camera
  external_clock:
    pin: GPIO15
    frequency: 20MHz
  i2c_pins:
    sda: GPIO4
    scl: GPIO5
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13
  #reset_pin: GPIO15
  resolution: 320x240
  jpeg_quality: 10
